POST localhost:3000 HTTP/1.1
Content-Type: application/json

{
    "asas":"asasas"
}
###
POST localhost:3000 HTTP/1.1
Content-Type: "application/json"

{
    Id: string;
    Title: string | null;
    Where: string;
    From: string;
    Notes: string;
}